name: 'Discord Action'
description: 'Adds a Message to a Discord channel via webhooks'
inputs:
  webhook:
    description: 'The Discord webhook'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
